[package]
name = "raymarch"
version = "0.1.0"
authors = ["Arden Rasmussen <ardenisthebest@gmail.com>"]
edition = "2018"

[dependencies]
log = "*"
fern = {version = "*", features=["colored"]}
chrono = "*"
nalgebra = "*"
image = "*"
typed-builder = "*"
rayon = "*"